.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "NUCLEUS" "1" "July 2016" "" ""
.
.SH "NAME"
\fBnucleus\fR \- user authentification tokens distribution service
.
.SH "DESCRIPTION"
\fInucleus\fR is service for distribution user authentification tokens basing on third\-party OAuth services\.
.
.P
\fInucleus\fR don\'t know how user will be authentificated, \fInucleus\fR know only one \- user can be authentificated and when new user visits index page, \fInucleus\fR will give to user a choose of how he will authentificate basing on OAuth providers that described in configuration file\.
.
.P
When user click at a login button \'Authorize using %service%\', \fInucleus\fR will redirect user to service\'s authorization gateway and after successfull/failed authorization user will be redirected to \fInucleus\fR callback URL\.
.
.P
At that moment \fInucleus\fR will create unique access token for specified user (if not created already), that token will be used for next authentifications between user and \fInucleus\fR\.
.
.P
If another external service supports authentification using \fInucleus\fR than user will pass secret token to that service as password, and that service will go to the nucleus and send provided token, nucleus will token and send information about user, if specified token really exists in database\.
.
.P
This method provides way for fast authentification, because \fInucleus\fR doesn\'t communicates with external services for checking user access\. User authorizes only once and uses authentification token everywhere\.
.
.SH "SYNOPSIS"
.
.nf

nucleus [\-\-config <path>]
nucleus \-h | \-\-help
nucleus \-\-version
.
.fi
.
.SH "OPTIONS"
\fB\-c, \-\-config \fIpath\fR\fR
.
.br
Use specified configuration file instead of default \fB/etc/nucleus/nucleus\.conf\fR\.
.
.P
\fB\-h, \-\-help\fR
.
.br
Show program help\.
.
.P
\fB\-\-version\fR
.
.br
Show version of program\. This value can be equal to \fB[manual build]\fR if nucleus has been installed using \fBgo get\fR or \fBgo install\fR instead of using system\-wide package manager\. Don\'t be a stupid, use packages, it will save human resources in future\.
.
.SH "CONFIGURATION"
\fInucleus\fR must be configured before starting, configuration file should be located in \fB/etc/nucleus/nucleus\.conf\fR, but this path can be changed using \fB\-\-config\fR flag, configuration file must be written in TOML format using following template:
.
.IP "" 4
.
.nf

[web]
  listen = ":80"
[database]
  url = "mongodb://localhost/dbname"
[[oauth]]
  name                = "Enterprise Service"
  slug                = "office"
  basic_url           = "http://intranet\.local/"
  consumer            = "consumer"
  key_file            = "/etc/nucleus/intranet\.key"
  session_url         = "/api/session"
  user_url            = "/api/user"
  request_token_url   = "/api/token/request"
  authorize_token_url = "/api/token/authorize"
  access_token_url    = "/api/token/access"
.
.fi
.
.IP "" 0
.
.P
As you can see, you must pass data source name for mongodb database in specified format:
.
.IP "" 4
.
.nf

mongodb://[user@]hostname[:port][,[user2@]hostname2[:port2]]/[database]
.
.fi
.
.IP "" 0
.
.P
Of course, \fBnucleus\fR will not crash if any of database host dies down, \fBnucleus\fR will ping database, properly catch database error if any, and try to reestablish database connection\.
.
.SH "REPRESENTATIONAL STATE TRANSFER APPLICATION INTERFACE"
.
.SS "GET /api/v1/user"
Authentificate user and retrieve information about user\.
.
.P
Authentification token should be passed as Basic Authorization password or using Cookie \fBtoken\fR header\.
.
.P
\fBRESPONSE STATUSES\fR
.
.IP "\(bu" 4
\fB401 Unathorized\fR
.
.br
User with specified token doesn\'t exists or token has been revoked by user\.
.
.IP "\(bu" 4
\fB200 OK\fR
.
.br
User authentificated\.
.
.IP "" 0
.
.SH "MAINTAINER"
Egor Kovetskiy \fIe\.kovetskiy@office\.ngs\.ru\fR
